### ISSUE TITLE
Underpromotion bug

### ISSUE THREAD

**Issue by SzotsGabor** [ChizhovVadim/CounterGo#1]
In a tournament under Fritz 15 Counter 2.0.1 64-bit stopped playing after an underpromotion by the opponent. This happened 5 times.

**Comment by ChizhovVadim** [comment]
Fixed, Counter v2.0.2

**Comment by SzotsGabor** [comment]
Thanks Vadim. Are there other differences between them or can 2.0.1 and 2.0.2 results merged?

**Comment by ChizhovVadim** [comment]
Counter 2.0.2 has higher node per seconds if using more than 1 CPU core. Theoretically it should give ELO increase. No differences with Counter 2.0.1 if only 1 CPU using.
